modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Kyagara/fred/issues"
license = "MIT"

[[mods]]
modId = "fred"
version = "${version}"
displayName = "Fred"
authors = "Kyagara"
description = '''
Utility mod with quality of life features and joke features.
'''
logoFile = "assets/fred/icon.png"

[[mixins]]
config = "fred.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.fred]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fred]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.72,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fred]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
